#!/usr/bin/env python3
"""Generate the revised paper's LaTeX tables from v2 results.

Every main-text result table is written by this script; the labelled
exceptions (v1 reference times, the AG News projection) are marked in the
captions (single
source of truth). Output: v2/paper/Quantum_Optimizer_Benchmarking/tables/*.tex

Tables:
  tab_cv_main.tex        CV: 6 configs x 6 arms, mean+-std over 5 seeds
  tab_factorial.tex      RoBERTa 2x2 factorial cells + effect estimates
  tab_ngd.tex            configured NGD vs AdamW cells (per dataset + pooled)
  tab_qpso_cost.tex      measured cost of direct stochastic QPSO adaptation
  tab_tabular_mlp.tex    tabular MLP benchmark
  tab_hessian.tex        Dominant Hessian-curvature summary by arm
"""

import json
import math
from collections import defaultdict
from pathlib import Path
from statistics import mean, stdev

BASE = Path(__file__).resolve().parents[2]
RUNS = BASE / "runs"
OUT = BASE / "paper" / "Quantum_Optimizer_Benchmarking" / "tables"
OUT.mkdir(parents=True, exist_ok=True)

STATS = json.loads((RUNS / "stats_summary.json").read_text())


def load():
    rows = []
    for p in RUNS.glob("*/**/result.json"):
        if "smoke" in str(p):
            continue
        try:
            r = json.loads(p.read_text())
        except Exception:
            continue
        if r.get("tag") == "smoke":
            continue
        rows.append(r)
    return rows


ROWS = load()


def sel(domain, dataset, model, arm_pred):
    by_seed = {}
    for r in ROWS:
        if (r["domain"], r["dataset"], r.get("model")) != (domain, dataset, model):
            continue
        if arm_pred(r):
            by_seed[r["seed"]] = r
    return list(by_seed.values())


def ms(rs, key="test_accuracy", pct=True, digits=None):
    vals = [r[key] for r in rs if r.get(key) is not None and math.isfinite(r[key])]
    if not vals:
        return "--"
    f = 100 if pct else 1
    d = digits if digits is not None else (1 if pct else 2)
    m = mean(vals) * f
    s = (stdev(vals) if len(vals) > 1 else 0.0) * f
    mark = ""
    if any(r.get("collapsed") for r in rs):
        n_c = sum(1 for r in rs if r.get("collapsed"))
        mark = f"$^{{\\dagger {n_c}/{len(rs)}}}$"
    return f"{m:.{d}f}\\,$\\pm$\\,{s:.{d}f}{mark}"


def opt_is(name):
    return lambda r: r["optimizer"] == name


# ------------------------------------------------------------------ CV main
def cv_main():
    configs = [("Fashion-MNIST", "fashion_mnist", "SimpleCNN"),
               ("Fashion-MNIST", "fashion_mnist", "ResNet18"),
               ("CIFAR-10", "cifar10", "SimpleCNN"),
               ("CIFAR-10", "cifar10", "ResNet18"),
               ("CIFAR-100", "cifar100", "SimpleCNN"),
               ("CIFAR-100", "cifar100", "ResNet18")]
    arms = [("SGD", "sgd"), ("Adam", "adam"), ("AdamW", "adamw"),
            ("NGD", "ngd"), ("HP-QNG", "ctrl_qng_hp"), ("SPSA", "spsa")]
    L = [
        "% AUTO-GENERATED by analysis/make_tables.py -- do not edit by hand",
        "\\begin{table*}[t]\\centering\\tiny",
        "\\setlength{\\tabcolsep}{1pt}",
        "\\caption{CV benchmark, v2 clean rerun: test accuracy (\\%, mean $\\pm$ std over seeds \\{42,1337,2025,7,123\\}). "
        "NGD = diagonal squared-minibatch-gradient preconditioner (classical QNG analog); HP-QNG = the hyperparameter-control "
        "configuration from the v1 NLP/tabular ``QNG-inspired'' recipe "
        "(Section~\\ref{sec:hp_controls}); SPSA = genuine Spall SPSA. "
        "$\\dagger$\\,$k/n$: $k$ of $n$ runs collapsed (NaN loss, aborted after three consecutive non-finite epochs; scored at final state).}",
        "\\label{tab:cv_main}",
        "\\begin{tabular}{l" + "c" * len(arms) + "}",
        "\\toprule",
        "Configuration & " + " & ".join(a[0] for a in arms) + " \\\\",
        "\\midrule",
    ]
    for disp, ds, model in configs:
        cells = [ms(sel("cv", ds, model, opt_is(code))) for _, code in arms]
        L.append(f"{disp} / {model} & " + " & ".join(cells) + " \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    (OUT / "tab_cv_main.tex").write_text("\n".join(L))


# ------------------------------------------------------------- factorial
def cell_pred(lr, wd):
    def p(r):
        if r["optimizer"] == "adamw" and abs(r["lr"] - lr) < 1e-12 and \
           abs(r.get("opt_kwargs", {}).get("weight_decay", 0.01) - wd) < 1e-9:
            return True
        if r["optimizer"] == "ctrl_qng_hp" and abs(lr - 1e-5) < 1e-12 and wd == 0.05:
            return True
        return False
    return p


def factorial():
    """Transposed layout (datasets as columns) so the table fits the text width."""
    ds_names = [("SST-2", "sst2"), ("IMDb", "imdb"), ("AG News", "ag_news")]
    cells_rows = [
        ("$\\eta{=}2\\mathrm{e}{-5}$, $\\lambda{=}0.01$ (v1 baseline)", 2e-5, 0.01),
        ("$\\eta{=}2\\mathrm{e}{-5}$, $\\lambda{=}0.05$", 2e-5, 0.05),
        ("$\\eta{=}1\\mathrm{e}{-5}$, $\\lambda{=}0.01$", 1e-5, 0.01),
        ("$\\eta{=}1\\mathrm{e}{-5}$, $\\lambda{=}0.05$ (v1 ``QNG'')", 1e-5, 0.05),
    ]
    eff_rows = [("$\\eta$ effect", "lr"), ("$\\lambda$ effect", "wd"),
                ("interaction", "interaction")]

    def fmt_eff(e):
        stars = "*" if e["p"] < 0.05 else ""
        return (f"{e['mean']*100:+.2f}{stars} "
                f"{{\\scriptsize[{e['ci'][0]*100:+.2f},{e['ci'][1]*100:+.2f}]}}")

    L = [
        "% AUTO-GENERATED by analysis/make_tables.py",
        "\\begin{table}[t]\\centering\\tiny",
        "\\setlength{\\tabcolsep}{1pt}",
        "\\caption{RoBERTa $2\\times2$ factorial decomposition of the original ``QNG-inspired'' configuration. "
        "Upper block: cell means (test accuracy \\%, $\\pm$ std, $n{=}5$ seeds). "
        "Lower block: seed-paired effect estimates in accuracy points with $t$-based 95\\% "
        "CIs (the percentile bootstrap is anticonservative at $n{=}5$ and is reserved for "
        "the pooled comparisons); * marks unadjusted paired-$t$ $p<0.05$ for the three "
        "planned factorial contrasts per dataset. None of the starred contrasts survives "
        "Holm correction within the nine-contrast factorial family; the "
        "small-cluster sensitivity analysis is reported in "
        "Section~\\ref{sec:res_factorial}.}",
        "\\label{tab:factorial}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        " & " + " & ".join(d for d, _ in ds_names) + " \\\\",
        "\\midrule",
    ]
    for label, lr, wd in cells_rows:
        vals = [ms(sel("nlp", ds, "roberta", cell_pred(lr, wd)), digits=2) for _, ds in ds_names]
        L.append(f"{label} & " + " & ".join(vals) + " \\\\")
    L.append("\\midrule")
    for label, key in eff_rows:
        vals = [fmt_eff(STATS["factorial"][ds][key]) for _, ds in ds_names]
        L.append(f"{label} & " + " & ".join(vals) + " \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT / "tab_factorial.tex").write_text("\n".join(L))


# ------------------------------------------------------------------ NGD
def ngd_table():
    ds_names = [("SST-2", "sst2"), ("IMDb", "imdb"), ("AG News", "ag_news")]
    L = [
        "% AUTO-GENERATED by analysis/make_tables.py",
        "\\begin{table}[t]\\centering\\tiny",
        "\\setlength{\\tabcolsep}{1pt}",
        "\\caption{Configured diagonal second-moment NGD on RoBERTa vs the two anchor AdamW cells "
        "(test acc.\\ \\%, $n{=}5$). $\\Delta$: seed-paired mean difference (pt); "
        "* marks unadjusted paired-$t$ $p<0.05$. "
        "The $\\Delta$ columns report point estimates; their $t$-based intervals are in the "
        "released summary. Pooled rows: Wilcoxon signed-rank over all 15 "
        "seed-pairs with bootstrap 95\\% CIs and are descriptive because the pairs form "
        "three dataset clusters. For NGD vs the v1-QNG cell, the dataset-level "
        "random-effects point estimate is $-0.38$\\,pt (modified Hartung--Knapp "
        "95\\% CI $[-1.09,+0.32]$, $p{=}0.144$; exact sign-flip $p{=}0.25$). "
        "The baseline comparison is heterogeneous ($Q$-test $p{=}0.002$); its "
        "dataset-level estimate is $+0.27$\\,pt (95\\% CI $[-1.40,+1.93]$, "
        "$p{=}0.561$).}",
        "\\label{tab:ngd}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Dataset & NGD & $\\Delta$ vs v1-QNG cell & $\\Delta$ vs baseline \\\\",
        "\\midrule",
    ]
    for disp, ds in ds_names:
        ngd = ms(sel("nlp", ds, "roberta", opt_is("ngd")), digits=2)
        e = STATS["ngd"][ds]
        def f(x):
            s = "*" if x["p_paired_t"] < 0.05 else ""
            return f"{x['mean_diff']*100:+.2f}{s}"
        L.append(f"{disp} & {ngd} & {f(e['vs_v1qng'])} & {f(e['vs_baseline'])} \\\\")
    pq = STATS["ngd"]["pooled_vs_v1qng"]
    pb = STATS["ngd"]["pooled_vs_baseline"]
    def pooled_cell(x):
        return (f"{x['mean_diff']*100:+.2f} "
                f"{{\\scriptsize[{x['ci'][0]*100:+.2f},{x['ci'][1]*100:+.2f}]}} "
                f"($p{{=}}{x['p_wilcoxon']:.3f}$)")
    L += ["\\midrule",
          f"Pooled (Wilcoxon) & -- & {pooled_cell(pq)} & {pooled_cell(pb)} \\\\",
          "\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT / "tab_ngd.tex").write_text("\n".join(L))


# ------------------------------------------------------------------ cost
def cost_table():
    def t(domain, ds, model, arm):
        rs = sel(domain, ds, model, opt_is(arm))
        return mean(r["training_time_seconds"] for r in rs) / 3600 if rs else None

    rows = [
        ("LSTM / SST-2", t("nlp", "sst2", "lstm", "qpso"), 1435 / 3600, "chance (49.1)"),
        ("LSTM / IMDb", t("nlp", "imdb", "lstm", "qpso"), 1139 / 3600, "chance (50.1)"),
        ("\\emph{LSTM / AG News}$^{\\ast}$", 26.9, 3718 / 3600, "\\emph{not run (projected)}"),
        ("SimpleCNN / Fashion", t("cv", "fashion_mnist", "SimpleCNN", "qpso"),
         t("cv", "fashion_mnist", "SimpleCNN", "adam"), "near chance (16.2)"),
        ("SimpleCNN / CIFAR-10", t("cv", "cifar10", "SimpleCNN", "qpso"),
         t("cv", "cifar10", "SimpleCNN", "adam"), "near chance (11.8)"),
    ]
    L = [
        "% AUTO-GENERATED by analysis/make_tables.py",
        "\\begin{table}[t]\\centering\\small",
        "\\caption{Measured and projected wall-clock cost of the direct stochastic-minibatch QPSO adaptation (10 particles) against Adam "
        "on a single T4 GPU, with resulting accuracy. QPSO hours are per-run means over "
        "each cell's completed runs ($n{=}3$; Fashion-MNIST $n{=}5$). Adam references: "
        "SimpleCNN rows are v2 measurements ($n{=}5$); LSTM rows are the v1-campaign "
        "measurements on the same GPU model (the v2 campaign ran no LSTM Adam arm). "
        "The spread between the two measured LSTM ratios reflects those v1 "
        "reference times---which differ mainly through evaluation-set size rather than "
        "optimizer behaviour---while QPSO's own per-step cost is nearly identical on both "
        "tasks (1.61 vs 1.62\\,s) and is dominated by host-side swarm updates rather than "
        "forward passes (Section~\\ref{sec:optimization_methods}). $^{\\ast}$The AG News row projects QPSO's measured per-step "
        "cost onto the AG News step count; the run was not executed and contributes "
        "to no accuracy statistic. This measured infeasibility motivates restricting "
        "the population method to small models.}",
        "\\label{tab:qpso_cost}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Config & QPSO (h/run) & Adam (h/run) & QPSO outcome \\\\",
        "\\midrule",
    ]
    for name, tq, ta, note in rows:
        tq_s = f"{tq:.1f}" if tq else "--"
        ta_s = f"{ta:.2f}" if ta else "--"
        ratio = f" ({tq/ta:.0f}$\\times$)" if tq and ta else ""
        L.append(f"{name} & {tq_s}{ratio} & {ta_s} & {note} \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT / "tab_qpso_cost.tex").write_text("\n".join(L))


# ------------------------------------------------------------- tabular MLP
def tabular_mlp():
    arms = [("SGD", "sgd"), ("Adam", "adam"), ("AdamW", "adamw"), ("NGD", "ngd"),
            ("HP-QNG", "ctrl_qng_hp"), ("SPSA", "spsa"), ("QPSO", "qpso")]
    L = [
        "% AUTO-GENERATED by analysis/make_tables.py",
        "\\begin{table*}[t]\\centering\\tiny",
        "\\setlength{\\tabcolsep}{1pt}",
        "\\caption{Tabular MLP benchmark (v2): the neural optimizer comparison for the "
        "tabular domain (mean $\\pm$ std, $n{=}5$ seeds). Adult/HIGGS: test accuracy (\\%); "
        "California Housing: test RMSE. `--': all five runs diverged to "
        "non-finite loss (SPSA on California Housing). The 17 arm-vs-Adam tests in this "
        "family are exploratory and reported unadjusted; seven of the eight nominally "
        "significant ones survive Holm correction within the family, the exception being "
        "SGD on HIGGS (adj.\\ $p{=}0.41$).}",
        "\\label{tab:tabular_mlp}",
        "\\begin{tabular}{l" + "c" * len(arms) + "}",
        "\\toprule",
        "Dataset & " + " & ".join(a[0] for a in arms) + " \\\\",
        "\\midrule",
    ]
    for disp, ds, key, pct in [("Adult", "adult", "test_accuracy", True),
                               ("HIGGS", "higgs", "test_accuracy", True),
                               ("California (RMSE)", "california_housing", "test_rmse", False)]:
        cells = [ms(sel("tabular", ds, "MLP", opt_is(code)), key=key, pct=pct)
                 for _, code in arms]
        L.append(f"{disp} & " + " & ".join(cells) + " \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    (OUT / "tab_tabular_mlp.tex").write_text("\n".join(L))


# ------------------------------------------------------------------ hessian
def hessian_table():
    groups = defaultdict(list)
    for p in RUNS.glob("*/**/hessian.json"):
        h = json.loads(p.read_text())
        value = h.get("dominant_rayleigh_first", h["lambda_max"])
        groups[(h["dataset"], h["model"], h["arm"])].append(value)
    arms = [("Adam", "adam"), ("AdamW", "adamw"), ("SGD", "sgd"),
            ("NGD", "ngd"), ("HP-QNG", "ctrl_qng_hp")]
    configs = [("Fashion-MNIST", "fashion_mnist"), ("CIFAR-10", "cifar10"),
               ("CIFAR-100", "cifar100")]
    L = [
        "% AUTO-GENERATED by analysis/make_tables.py",
        "\\begin{table}[t]\\centering\\small",
        "\\caption{Dominant Hessian-curvature estimate at trained endpoints "
        "(first Rayleigh estimate returned by power iteration with deflation; mean "
        "$\\pm$ std over seeds \\{42,1337,2025\\}). The analysis uses the three common "
        "seeds of the v1/v2 campaigns and one 512-sample batch shared across arms and "
        "seeds within each dataset during the archived analysis. The routine targets "
        "large-magnitude directions and does not certify positive, algebraically ordered "
        "eigenvalues, local minima, or condition numbers. Smaller cell means occur for "
        "Adam/AdamW on ResNet18, while the ordering varies on SimpleCNN "
        "(Section~\\ref{sec:disc_curvature}).}",
        "\\label{tab:hessian}",
        "\\begin{tabular}{llccccc}",
        "\\toprule",
        "Dataset & Model & " + " & ".join(a[0] for a in arms) + " \\\\",
        "\\midrule",
    ]
    for disp, ds in configs:
        for model in ["SimpleCNN", "ResNet18"]:
            cells = []
            for _, arm in arms:
                v = groups.get((ds, model, arm))
                if v and len(v) > 1:
                    cells.append(f"{mean(v):.0f}\\,$\\pm$\\,{stdev(v):.0f}")
                elif v:
                    cells.append(f"{mean(v):.0f}")
                else:
                    cells.append("--")
            L.append(f"{disp} & {model} & " + " & ".join(cells) + " \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (OUT / "tab_hessian.tex").write_text("\n".join(L))


if __name__ == "__main__":
    cv_main()
    factorial()
    ngd_table()
    cost_table()
    tabular_mlp()
    hessian_table()
    for f in sorted(OUT.glob("*.tex")):
        print(f"wrote {f.name}")
